import chess
from policies import *
from abc import ABC, abstractmethod

board = chess.Board()

class Player:
    def __init__(self, color):
        self.color = color

    def make_move(self, board):
        move = input(f"Player {self.color}, enter your move: ")
        try:
            board.push_uci(move)
        except ValueError:
            print("Invalid move. Try again.")
            self.make_move(board)


class Bot(ABC):
    def __init__(self, policy: callable):
        """
        Initialize the Bot with a color and a policy function.
        :param policy: A callable function that takes a chess board and returns a move in UCI.
        """
        if policy is None:
            raise ValueError("Policy function must be provided.")
        self.policy = policy

    def make_move(self, board: chess.Board):
        # Simple AI: Random move
        score, move = self.policy(board)
        if move not in board.legal_moves:
            raise Exception(f"Illegal move generated by policy. Move: {move}")
        board.push(move)
        print(f"Bot played: {move}")


class TreeSearchBot(Bot, ABC):
    def __init__(self, evaluate_board: callable, depth: int = 5):
        policy = lambda board: tree_search(board, evaluate_board, depth)
        super().__init__(policy)
        self.depth = depth
        self.evaluate_board = evaluate_board


class GreedyBot(TreeSearchBot):
    def __init__(self, depth = 5):
        super().__init__(get_material_difference, depth)


def start_game(white_player: Player, black_player: Player):
    while not board.is_game_over():
        if board.turn:
            white_player.make_move(board)
        else:
            black_player.make_move(board)
        print(board)
        print("\n")
    
    print_result(board.outcome())


def print_result(outcome: chess.Outcome):
    match outcome.termination:
        case chess.Termination.CHECKMATE:
            print("Checkmate!")
        case chess.Termination.STALEMATE:
            print("Stalemate!")
        case chess.Termination.INSUFFICIENT_MATERIAL:
            print("Insufficient material!")
        case chess.Termination.FIFTY_MOVES:
            print("Fifty moves rule!")
    
    print(f"Result: {outcome.result()}")
    

if __name__ == "__main__":
    white_player = Player("White")
    black_player = GreedyBot()
    start_game(white_player, black_player)
